import type { AppProps } from 'next/app';
import Head from 'next/head';

import theme from '@common/muiTheme';
import { ThemeProvider } from '@mui/material';
import '@styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<ThemeProvider theme={theme}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Component {...pageProps} />
			</ThemeProvider>
		</>
	);
}

export default MyApp;
