import Head from 'next/head';

import '@styles/globals.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from '@mui/material';
import theme from '@common/muiTheme';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ThemeProvider theme={theme}>
				{' '}
				<Component {...pageProps} />
			</ThemeProvider>
		</>
	);
}

export default MyApp;
